defaults:
  - model: model_conf
  - data: tofu
  - eval: tofu
  - trainer: custom
  - collator: DataCollatorForSupervisedDataset
  - hydra: default
  - paths: default
  - _self_

mode: unlearn
task_name: tofu
