config = {
    "learning": {
        "lr": 0.0003,
        "max_grad_norm": 1.0,
        "total_timesteps": 209715200,
        "num_train_envs": 2048,
        "num_minibatches": 32,
        "gamma": 0.995,
        "update_epochs": 8,
        "clip_eps": 0.2,
        "gae_lambda": 0.9,
        "ent_coef": 0.01,
        "anneal_lr": False,
        "vf_coef": 0.5,
        "num_steps": 256,
    },
    "ued": {
        "ratio_from_buffer": 0.5,
        "batch_size": 256,
        "num_batches": 1,
        "rollout_steps": 256,
        "num_to_save": 256,
        "buffer_update_frequency": 1,
        "learnability_correction": True,
    },
    "seed": 0,
}
